version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: Backtest_Pulse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Alliswell@28
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./sql:/app/sql
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "max_connections=200"]

  app:
    build: .
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=Backtest_Pulse
      - PGUSER=postgres
      - PGPASSWORD=Alliswell@28
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: